import { requireAuth } from "@/actions/auth/require.actions";
import { LogoutButton } from "@/components/LogoutBtn";
import { Button } from "@/components/ui/button";
import { prisma } from "@/lib/prisma";
import { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};
export default async function DashboardLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <div className="max-w-screen-2xl m-auto">
      {/* Main Content */}
      <main className="">{children}</main>
    </div>
  );
}
