import { requireAuth } from "@/actions/auth/require.actions";
import { LogoutButton } from "@/components/LogoutBtn";
import { Button } from "@/components/ui/button";
import { prisma } from "@/lib/prisma";
import { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default async function DashboardLayout({
  children,
}: {
  children: ReactNode;
}) {
  const userId = await requireAuth();
  const store = await prisma.store.findFirst({
    where: { userId },
  });

  if (!store) {
    redirect("/");
  }

  return (
    <div className="min-h-screen flex">
      {/* Sidebar */}
      <aside className="w-64 bg-secondary text-secondary-foreground p-4 border-l-2 flex flex-col">
        {/* عنوان المتجر */}
        <h2 className="py-3 text-3xl font-bold text-center">
          <Link href={`/dashboard`}>{store.name}</Link>
        </h2>

        <hr className="my-3" />

        {/* روابط الداشبورد */}
        <div className="flex flex-col gap-3">
          <Button asChild className="w-full">
            <Link href={`/dashboard/products`}>المنتجات</Link>
          </Button>

          <Button asChild className="w-full">
            <Link href={`/dashboard/categories`}>الفئات</Link>
          </Button>
        </div>

        {/* زر تسجيل الخروج في آخر الـ aside */}
        <div className="mt-auto pt-6 flex flex-col gap-2">
          <Button asChild className="w-full">
            <Link href={`/store/${store.slug}`}>زيارة المتجر</Link>
          </Button>
          <LogoutButton />
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 p-6">{children}</main>
    </div>
  );
}
